config/routes.rb
Caz::Engine.routes.draw do
  root to: 'dashboard#index'

  resources :posts, only: [:new, :create, :index, :edit, :update, :destroy], param: :slug
  resources :post_slugs, only: [:create]

  resources :pages, only: [:new, :create, :index, :edit, :update, :destroy], param: :slug
  resources :categories
end

app/models/caz/category.rb
module Caz
  class Category < ActiveRecord::Base
    belongs_to :parent, class_name: 'Category'
    has_many :posts

    validates :name, presence: true
  end
end

app/models/caz/entry.rb
module Caz
  class Entry < ActiveRecord::Base
    validates_presence_of :title, :slug
    has_many :entry_categories, dependent: :destroy
    has_many :categories, through: :entry_categories


    extend FriendlyId
    friendly_id :title, use: :slugged

    def self.types
      %w(Caz::Post Caz::Page)
    end

    def category_names
      categories.pluck(:name)
    end
  end
end

app/models/caz/entry_category.rb
module Caz
  class EntryCategory < ActiveRecord::Base
    belongs_to :category
    belongs_to :entry
  end
end

app/models/caz/entry_presenter.rb
module Caz
  class EntryPresenter < Burgundy::Item
    def category_names
      item.category_names.join(', ')
    end
  end
end

app/models/caz/page.rb
module Caz
  class Page < Entry
  end
end

app/models/caz/post.rb
module Caz
  class Post < Entry
  end
end

app/controllers/caz/application_controller.rb
module Caz
  class ApplicationController < ActionController::Base
    helper_method :js_metadata

    def js_metadata
      {
        post_slugs_path: post_slugs_path
      }.to_json
    end
  end
end

app/controllers/caz/categories_controller.rb
require_dependency "caz/application_controller"

module Caz
  class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    def index
      @categories = Category.all
    end

    def show
    end

    def new
      @category = Category.new
      @category_options = Category.pluck(:name, :id)
    end

    def edit
      @category_options = Category.pluck(:name, :id)
    end

    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to @category, notice: I18n.t('flashes.created', model: resource_name)
      else
        render :new
      end
    end

    def update
      if @category.update(category_params)
        redirect_to @category, notice: I18n.t('flashes.updated', model: resource_name)
      else
        render :edit
      end
    end

    def destroy
      @category.destroy
      redirect_to categories_url, notice: I18n.t('flashes.destroyed', model: resource_name)
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :parent_id)
    end

    def resource_name
      Category.model_name.human
    end
  end
end

app/controllers/caz/dashboard_controller.rb
class Caz::DashboardController < Caz::ApplicationController
  def index
  end
end

app/controllers/caz/entries_controller.rb
module Caz
  class EntriesController < ApplicationController
    helper_method :resource_name
    helper_method :edit_path
    helper_method :resource_path
    before_action :set_categories

    def index
      @entries = Burgundy::Collection.new(
        resource_class.all,
        resource_presenter
      )
    end

    def new
      @entry = resource_class.new
    end

    def create
      @entry = resource_class.new(entry_params)
      if @entry.save
        redirect_to collection_path, notice: I18n.t('flashes.created', model: resource_name.human)
      else
        render 'new'
      end
    end

    def update
      @entry = resource_class.friendly.find(params[:slug])
      if @entry.update(entry_params)
        redirect_to collection_path, notice: I18n.t('flashes.updated', model: resource_name.human)
      else
        render 'edit'
      end
    end

    def edit
      @entry = resource_class.friendly.find(params[:slug])
    end

    def destroy
      @entry = resource_class.friendly.find(params[:slug])
      @entry.destroy
      redirect_to collection_path, notice: I18n.t('flashes.destroyed', model: resource_name.human)
    end

    protected
    def set_categories
      @categories = Category.all
    end

    def collection_path
      self.send("#{resource_name.route_key}_path")
    end

    def edit_path(*args)
      self.send("edit_#{resource_name.singular_route_key}_path", *args)
    end

    def resource_path(*args)
      self.send("#{resource_name.singular_route_key}_path", *args)
    end

    def resource_class
      Entry
    end

    def resource_presenter
      EntryPresenter
    end

    def resource_name
      resource_class.model_name
    end

    def entry_params
      params.require(resource_name.param_key).permit(:title, :content, :slug, :category_ids=>[])
    end
  end
end

app/controllers/caz/pages_controller.rb
module Caz
  class PagesController < EntriesController
    protected

    def resource_class
      Page
    end

    def collection_path
      pages_path
    end
  end
end

app/controllers/caz/post_slugs_controller.rb
module Caz
  class PostSlugsController < ApplicationController
    def create
      @post = Post.new(title: params[:title])

      unless params[:title].empty?
        @post.send(:set_slug)
        render json: { slug: @post.slug }
      else
        render json: { slug: '' }
      end
    end
  end
end

app/controllers/caz/posts_controller.rb
module Caz
  class PostsController < EntriesController
    protected

    def resource_class
      Post
    end
  end
end

app/helpers/caz/application_helper.rb
module Caz
  module ApplicationHelper
    def new_link_for(model)
      link_to t('buttons.new', model: model.model_name.human),
        self.send("new_#{model.model_name.singular_route_key}_path")
    end

    def all_link_for(model)
      link_to t('buttons.all', model: model.model_name.human.pluralize),
        self.send("#{model.model_name.route_key}_path")
    end
  end
end

app/views/caz/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.select :parent_id do %>
      <%= options_for_select(@category_options) %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/caz/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/caz/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.parent %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/caz/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/caz/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <% if @category.parent.present? %>
    <strong>Parent:</strong>
    <%= @category.parent.name %>
  <% end %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/caz/dashboard/index.html.erb
<div class="grid-items">
  <div class="grid-item">
    <div class="grid-heading">
      <h1>Categorias</h1>
    </div>
    <div class=grid-content>
      <span class="pull-left">
        teste
      </span>
      <span class="pull-right">
        teste2
      </span>
      <span class="clearfix"></span>
    </div>
  </div>
  <div class="grid-item">
    <div class="grid-heading">
      <h1>Ùltimos inseridos</h1>
    </div>
    <div class=grid-content>
      <table class="table-minimal">
        <thead>
          <tr>
            <th>Header Cell 1</th>
            <th>Header Cell 2</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Row 1 Cell 1</td>
            <td>Row 1 Cell 2</td>
          </tr>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="grid-item">
    <div class="grid-heading">
      <h1>Estatísticas</h1>
    </div>
    <div class=grid-content>
      <span class="pull-left">
        teste
      </span>
      <span class="pull-right">
        teste2
      </span>
      <span class="clearfix"></span>
    </div>
  </div>
</div>

app/views/caz/entries/_form.html.erb
<%= form_for(@entry, html: { component: 'post_form', metadata: js_metadata }) do |f| %>
  <div class="main-fields">
    <% if @entry.errors.any? %>
      <ul>
        <% @entry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

    <%= f.text_field :title, placeholder: Caz::Entry.human_attribute_name(:title), class: 'title' %>
    <%= f.text_field :slug, placeholder: Caz::Entry.human_attribute_name(:slug), class: 'slug' %>
    <%= f.text_area :content, placeholder: Caz::Entry.human_attribute_name(:content) %>
    <%= f.submit t('buttons.save') %>
  </div>
  <aside>

    <div class="grid-items">
      <div class="grid-item">
        <div class="grid-heading">
          <h1><%= f.label :categories %></h1>
        </div>
        <div class=grid-content>
          <%= f.collection_check_boxes(:category_ids, @categories, :id, :name) do |i| %>
            <%= i.label do %>
              <%= i.check_box %>
              <%= i.object.name %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </aside>
<% end %>

app/views/caz/entries/edit.html.erb
<div class="entries">
  <h1><%= t('titles.edit', model: resource_name.human.downcase) %></h1>
  <%= render 'form' %>
</div>

app/views/caz/entries/index.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>
  <tbody>
    <% @entries.each do |entry| %>
      <tr id="item-<%= entry.slug %>">
        <td><%= link_to entry.title, edit_path(slug: entry.slug) %></td>
        <td><%= entry.category_names %></td>
        <td><%= link_to 'delete', resource_path(slug: entry.slug), method: :delete, class: 'delete-button' %></td>
      </tr>
    <% end %>
   </tbody>
 </table>

app/views/caz/entries/new.html.erb
<div class="entries">
  <h1><%= t('titles.add', model: resource_name.human.downcase) %></h1>
  <%= render 'form' %>
</div>

app/views/layouts/caz/_footer.html.erb
<footer class="footer">
  <div class="footer-text">
    © 2015 CMS Tracersoft.
  </div>
  <div class="footer-logo">
    <%= link_to 'http://www.tracersoft.com.br', target: '_blank' do %>
      <%= image_tag image_path('caz/tracer-logo.svg') %>
    <% end %>
  </div>
</footer>

app/views/layouts/caz/_nav.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <div class="navigation-logo">
      <a href="javascript:void(0)">
        <h2>Caz</h2> 
      </a>
  </div>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <% [Caz::Post, Caz::Page, Caz::Category].each do |model| %>
          <li class="nav-link more">
            <a href="javascript:void(0)"><%= model.model_name.human.pluralize %></a>
            <ul class="submenu">
              <li><%= new_link_for(model) %></li>
              <li class="divider"></li>
              <li><%= all_link_for(model) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/caz/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tingui</title>
  <%= stylesheet_link_tag    "caz/application", media: "all" %>
  <%= javascript_include_tag "caz/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
    <%= render 'layouts/caz/nav' %>
    <section class="content">
      <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: name %>
      <% end -%>
      <%= yield %>
    </section>
    <%= render 'layouts/caz/footer' %>
  </div>
</body>
</html>